### ISSUE TITLE
gomphotherium does not use $BROWSER envvar

### ISSUE THREAD

**Issue by johannboehme** [mrusme/gomphotherium#1]
First:
love your app!
Awesome vim like keybindings and the picture rendering is so awesome! 👍 

However i am using it in a wsl instance, and instead of opening toots with my windows chrome.exe which i set in my .profile via export $BROWSER, it opens a linux firefox in a forwarded x session.
Is there any way to customize the used browser, or could you default to $BROWSER?

PS:
d / u or f / b as shortcuts for scrolling pages would also be reeeeally nice!

**Comment by mrusme** [comment]
@johannboehme thank you, glad you like it! 👍🏼 I've submitted what could be a possible fix for the `open` issue you're experiencing. If you'd like feel free to check out HEAD and try it. :)

As for the d / u and f /b shortcuts, good idea, I will add them as well.

**Comment by mrusme** [comment]
u/b, d/f navigation was also implemented.
