### ISSUE TITLE
timeline strange output

### ISSUE THREAD

**Issue by sebastianschauenburg** [mrusme/gomphotherium#2]
When I run ```gomphotherium timeline``` from my bash shell, I get a lot of output and it ends like the following:

> ]▄[:#d6d8d7][#cccecd:]▄[:#d6d8d7][#cccecd:]▄[:#d6d8d7][#cccecd:]▄[:#d6d8d7][#cccecd:]▄[:#d6d8d7][#cccecd:]▄[:#d6d8d7][#cccecd:]▄[:#d6d8d7][#cccecd:]▄[:#d6d8d7][#cccecd:]▄[:#d6d8d7][#cccecd:]▄[:#d6d8d7][#cccecd:]▄[:#d6d8d7][#cccecd:]▄[:#d6d
> 8d7][#cccecd:]▄[:#d6d8d7][#cccecd:]▄[:#d6d8d7][#cccecd:]▄[:#d6d8d7][#cccecd:]▄[-:-:-]
> 
> [purple]↫ 0[-] [green]↻ 2[-] [yellow]★ 0[-] [grey]on Apr 7 at 11:10[-]

Running ```gomphotherium tui```, I'm presented with a blank interface, but I assume that will be solved, once the issue above is solved.

I'm running Ubuntu 20.04 with [awesome wm](https://awesomewm.org/), [st](https://st.suckless.org/) and bash. Which setting should I tweak and/or how can I get this awesome mastodon client running? Thanks in advance.

**Comment by mrusme** [comment]
The output is [tview](https://github.com/rivo/tview) formatting. Depending on what you're intending to do with it, you will need to reformat it to whatever output you need. This is not an issue.

As for the blank interface, I assume that you don't use the latest version from git but rather a released binary. The `timeline` command doesn't actually exist anymore, hence I believe that updating to the latest version will help fix the issue for you. This software is still v0.0.something, so don't put too much confidence into individual releases and better clone the repo and build it yourself. :-)
